[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  # Use the python runtime
  runtime = "python"
  included_files = ["backend/**", "grilli/**", "db.sqlite3", "manage.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200
