# Generated by Django 4.2.15 on 2024-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('person', models.CharField(choices=[('1-person', '1-person'), ('2-person', '2-person'), ('3-person', '3-person'), ('4-person', '4-person'), ('5-person', '5-person'), ('6-person', '6-person'), ('7-person', '7-person')], default='1-person', max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('08:00am', '08:00am'), ('09:00am', '09:00am'), ('010:00am', '010:00am'), ('011:00am', '011:00am'), ('012:00am', '012:00am'), ('01:00pm', '01:00pm'), ('02:00pm', '02:00pm'), ('03:00pm', '03:00pm'), ('04:00pm', '04:00pm'), ('05:00pm', '05:00pm'), ('06:00pm', '06:00pm'), ('07:00pm', '07:00pm'), ('08:00pm', '08:00pm'), ('09:00pm', '09:00pm'), ('010:00pm', '010:00pm')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
